services:
  zanemr-auth-service:
    image: zanemr-auth-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8081:8081"
    volumes:
      - ./src/main/resources/config:/config
    networks:
      - zanemr
    depends_on:
      - zanemr-auth-service-db
    command: ["java", "-jar", "app.jar"]

  zanemr-auth-service-db:
    build:
      context: ./postgres
    restart: always
    container_name: zanemr-auth-service-db
    env_file:
      - .env
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /var/apps/zanemr/data:/backup
    networks:
      - zanemr
    command:  "postgres -c config_file=/etc/postgresql/postgresql.conf"

volumes:
  pgdata:

networks:
  zanemr:
    external: true