services:
  iamis-api:
    image: iamis-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8081:8081"
    volumes:
      - ./src/main/resources/config:/config
    networks:
      - zanemr
    depends_on:
      - iamis-db
    command: [ "java", "-jar", "app.jar" ]

  iamis-db:
    build:
      context: ./postgres
    restart: always
    container_name: iamis-db
    env_file:
      - .env
    ports:
      - "6000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /var/apps/iamis/data:/backup
    networks:
      - zanemr
    command: "postgres -c config_file=/etc/postgresql/postgresql.conf"

volumes:
  pgdata:

networks:
  iamis:
    external: true