# Use OpenJDK 21 base image for Spring Boot 3
FROM openjdk:21-jdk

# Set the working directory
WORKDIR /

# Copy the JAR file generated by Spring Boot to the container
COPY build/libs/zanemr-auth-service-0.0.1-SNAPSHOT.jar app.jar


# Expose the port Spring Boot is running on
EXPOSE 8081

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
