services:
  zanemr-auth-service:
    image: zanemr-auth-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8081:8081"
    volumes:
      - ./src/main/resources/config:/config
    networks:
      - zanemr
    depends_on:
      - zanemr-auth-service-db
    command: ["java", "-jar", "app.jar"]

  zanemr-auth-service-db:
    image: postgres:15-alpine
    restart: always
    container_name: zanemr-auth-service-db
    env_file:
      - .env
    environment:
      - PG_RESTORE=${PG_RESTORE:-false}
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /var/apps/zanemr/data:/backup
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - zanemr
    command: >
      bash -c "
        if [ \"$$PG_RESTORE\" = \"true\" ] && [ -f /backup/zanemr-auth.sql ]; then
          echo 'Restoring database from backup...';
          pg_restore -U $$POSTGRES_USER -d $$POSTGRES_DB /backup/zanemr-auth.sql || psql -U $$POSTGRES_USER -d $$POSTGRES_DB < /backup/zanemr-auth.sql;
        fi;
        docker-entrypoint.sh postgres"

volumes:
  pgdata:

networks:
  zanemr:
    external: true