services:
  zanemr-auth-service:
    image: zanemr-auth-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8081:8081"
    volumes:
      - ./src/main/resources/config:/config
    networks:
      - zanemr
    depends_on:
      - zanemr-auth-service-db
    command: ["java", "-jar", "app.jar"]

  zanemr-auth-service-db:
    image: postgres:15-alpine
    restart: always
    container_name: zanemr-auth-service-db
    env_file:
      - .env
    environment:
      - PG_RESTORE=${PG_RESTORE:-false}
      - DATA_FILE=${DATA_FILE}
      - POSTGRES_INITDB_ARGS="--wal-level=logical"
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /var/apps/zanemr/data:/backup
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - zanemr
    command: >
      bash -c "
        if [ \"$$PG_RESTORE\" = \"true\" ] && [ -f \"$$DATA_FILE\" ]; then
          echo 'Restoring database from backup file: $$DATA_FILE';
          pg_restore -U $$POSTGRES_USER -d $$POSTGRES_DB \"$$DATA_FILE\" || psql -U $$POSTGRES_USER -d $$POSTGRES_DB < \"$$DATA_FILE\";
        fi;
        docker-entrypoint.sh postgres"

volumes:
  pgdata:

networks:
  zanemr:
    external: true