services:
  zanemr-auth-service:
    image: zanemr-auth-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8081:8081"
    volumes:
      - ./src/main/resources/config:/config
    networks:
      - zanemr
    depends_on:
      - zanemr-auth-service-db
    command: ["java", "-jar", "app.jar"]

  zanemr-auth-service-db:
    image: postgres:13-alpine
    restart: always
    container_name: zanemr-auth-service-db
    environment:
      - POSTGRES_DB=zanemr_authorization
      - POSTGRES_USER=zanemr
      - POSTGRES_PASSWORD=p@ssw0rd
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - zanemr

volumes:
  pgdata:

networks:
  zanemr:
    external: true