
#Super admin config
admin-email: admin@iamis.co.tz
admin-password: ${DEFAULT_ADMIN_PASSWORD:password}
spring:
  application:
    name: ${service-name}

  flyway:
    sql-migration-prefix:
    table: migrations
    out-of-order: true
    validate-on-migrate: true

  task:
    execution:
      thread-name-prefix: ${service-name}-task
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: ${service-name}-scheduling
      pool:
        size: 10
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
