
#Super admin config
admin-email: admin@zanemr.go.tz
admin-password: password
spring:

  flyway:
    sql-migration-prefix:
    table: migrations
    out-of-order: true
    validate-on-migrate: true

  cloud:
    refresh:
      enabled: false
    consul:
      discovery:
        prefer-ip-address: true
        enabled: true
        register: true
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: c204cb1e-1bcb-4615-a6f7-2021c33ff360
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
    admin:
      fail-fast: true
  task:
    execution:
      thread-name-prefix: ${service-name}-task
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: ${service-name}-scheduling
      pool:
        size: 10
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
