service-name: auth-dev

#front end web client url
web-client-url: http://localhost:4200
#This service configuration
service-port: 8081

#Database service configuration
db-server: 102.223.7.208
db-port: 5001
db-name: zanemr_authorization
db-username: zanemr
db-password: p@ssw0rd

#Consul service Discovery configuration
consul-server: 102.223.7.208
consul-port: 8500

#Kafka service configuration
kafka-server: 102.223.7.208
kafka-port: 9092

kafka-connect-server: 102.223.7.208
kafka-connect-port: 8083

spring:
  application:
    name: ${service-name}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${db-server}:${db-port}/${db-name}
    username: ${db-username}
    password: ${db-password}

  cloud:
    refresh:
      enabled: false
    consul:
      host: ${consul-server}
      port: ${consul-port}
      discovery:
        prefer-ip-address: true
        enabled: true
        register: true
  kafka:
    bootstrap-servers: ${kafka-server}:${kafka-port}
  task:
    execution:
      thread-name-prefix: ${service-name}-task
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: ${service-name}-scheduling
      pool:
        size: 10

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.oauth2: DEBUG
        web: INFO

server:
  port: ${service-port}

