service-name: iamis-api

#front end web client url
web-client-url: http://localhost:4200
#This service configuration
service-port: 8081

#Database service configuration
db-server: localhost
db-port: 6000
db-name: iamis-dev
db-username: iamis
db-password: p@ssw0rd

spring:
  application:
    name: ${service-name}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${db-server}:${db-port}/${db-name}
    username: ${db-username}
    password: ${db-password}

  task:
    execution:
      thread-name-prefix: ${service-name}-task
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: ${service-name}-scheduling
      pool:
        size: 10

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.oauth2: DEBUG
        web: INFO

server:
  port: ${service-port}

