#This service configuration
service-name: auth
service-port: 8081

#Database service configuration
db-server: zanemr-auth-service-db
db-port: 5432
db-name: zanemr_authorization
db-username: zanemr
db-password: p@ssw0rd

#Consul service Discovery configuration
consul-server: 102.223.7.208
consul-port: 8500

#Kafka service configuration
kafka-server: 102.223.7.208
kafka-port: 9092

spring:
  application:
    name: ${service-name}

  security:
    oauth2:
      authorizationserver:
        issuer: http://102.223.7.208:8081

  flyway:
    sql-migration-prefix:
    table: migrations
    out-of-order: true
    validate-on-migrate: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${db-server}:${db-port}/${db-name}
    username: ${db-username}
    password: ${db-password}

  cloud:
    refresh:
      enabled: false
    consul:
      host: ${consul-server}
      port: ${consul-port}
      discovery:
        prefer-ip-address: false
        enabled: true
        register: true
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
    admin:
      fail-fast: true
    bootstrap-servers: ${kafka-server}:${kafka-port}
  task:
    execution:
      thread-name-prefix: ${service-name}-task
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: ${service-name}-scheduling
      pool:
        size: 10

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.oauth2: DEBUG
        web: INFO

server:
  port: ${service-port}

