spring:
  application:
    name: authorization-service

  flyway:
    sql-migration-prefix:
    table: migrations
    out-of-order: true
    validate-on-migrate: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/zanemr_authorization
    username: postgres
    password: p@ssw0rd

#  cloud:
#    refresh:
#      enabled: false

#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        enabled: true
#        register: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.oauth2: DEBUG
        web: DEBUG

server:
  port: 9000
