spring:
  application:
    name: authorization

  flyway:
    sql-migration-prefix:
    table: migrations
    out-of-order: true
    validate-on-migrate: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/zanemr_authorization
    username: postgres
    password: p@ssw0rd

  cloud:
    refresh:
      enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        enabled: true
        register: true
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
    admin:
      fail-fast: true
    bootstrap-servers: localhost:9092
  task:
    execution:
      thread-name-prefix: zanemr-task
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: zanemr-scheduling
      pool:
        size: 10
logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.oauth2: DEBUG
        web: INFO

server:
  port: 8081
