spring:
  application:
    name: authorization

  flyway:
    sql-migration-prefix:
    table: migrations
    out-of-order: true
    validate-on-migrate: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/zanemr_authorization
    username: postgres
    password: p@ssw0rd

  cloud:
    refresh:
      enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        enabled: true
        register: true
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

logging:
  level:
    org:
      springframework:
        security: INFO
        security.oauth2: INFO
        web: INFO

server:
  port: 8081
