CREATE TABLE roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID                                    NOT NULL,
    name       VARCHAR(100),
    code       VARCHAR(50),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(120),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(120),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(120),
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uc_roles_uuid UNIQUE (uuid),
    CONSTRAINT uc_roles_code UNIQUE (code),
    CONSTRAINT uc_roles_name UNIQUE (name)
);


CREATE TABLE users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid             UUID                                    NOT NULL,
    email            VARCHAR(120)                            NOT NULL,
    password         VARCHAR(255)                            NOT NULL,
    first_name       VARCHAR(120)                            NOT NULL,
    middle_name      VARCHAR(120),
    last_name        VARCHAR(120),
    sex              VARCHAR(10),
    mobile_number    VARCHAR(20),
    is_active        BOOLEAN,
    password_changed BOOLEAN,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(120),
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_by       VARCHAR(120),
    deleted_at       TIMESTAMP WITHOUT TIME ZONE,
    deleted_by       VARCHAR(120),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_email UNIQUE (email),
    CONSTRAINT uc_users_uuid UNIQUE (uuid)
);

CREATE TABLE authorities
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID                                    NOT NULL,
    name        VARCHAR(120),
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(120),
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_by  VARCHAR(120),
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_by  VARCHAR(120),
    CONSTRAINT pk_authorities PRIMARY KEY (id),
    CONSTRAINT uc_authorities_uuid UNIQUE (uuid)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id),
    CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE role_authorities
(
    authority_id BIGINT NOT NULL,
    role_id      BIGINT NOT NULL,
    CONSTRAINT pk_role_authorities PRIMARY KEY (authority_id, role_id),
    CONSTRAINT fk_rolaut_on_authority FOREIGN KEY (authority_id) REFERENCES authorities (id),
    CONSTRAINT fk_rolaut_on_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE menu_groups
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID                                    NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    module     VARCHAR(255)                            NOT NULL,
    icon       VARCHAR(255),
    sort_order INTEGER                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(255),
    CONSTRAINT pk_menu_groups PRIMARY KEY (id),
    CONSTRAINT uc_menu_groups_uuid UNIQUE (uuid)
);

CREATE TABLE menu_items
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID                                    NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    icon              VARCHAR(255),
    state             VARCHAR(255)                            NOT NULL,
    sort_order        INTEGER                                 NOT NULL,
    translation_label VARCHAR(255),
    menu_group_id     BIGINT                                  NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted_by        VARCHAR(255),
    CONSTRAINT pk_menu_items PRIMARY KEY (id),
    CONSTRAINT uc_menu_items_uuid UNIQUE (uuid),
    CONSTRAINT FK_MENU_ITEMS_ON_MENU_GROUP FOREIGN KEY (menu_group_id) REFERENCES menu_groups (id)
);

CREATE TABLE menu_item_authorities
(
    authority_id BIGINT NOT NULL,
    menu_item_id BIGINT NOT NULL,
    CONSTRAINT pk_menu_item_authorities PRIMARY KEY (authority_id, menu_item_id),
    CONSTRAINT fk_meniteaut_on_authority FOREIGN KEY (authority_id) REFERENCES authorities (id),
    CONSTRAINT fk_meniteaut_on_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_items (id)
);


INSERT INTO users (id, uuid, email, password, first_name, middle_name, last_name, sex, mobile_number, is_active, password_changed, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by)
VALUES (1, '43c2acb8-9b2b-4948-be5b-491d9368697d', 'admin@zanemr.go.tz', '$2a$10$7tMyVIbqzln6HVTYbpag6u0AJe7KuJ1lA5PZGs8cK7h5lxLPmMjIO', 'Admin', null, null, null, null, true, false, null, 'SYSTEM', null, null, null, null);

INSERT INTO roles (id, uuid, name, code, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by)
VALUES (1, '2cfc0705-ab2c-48d9-bf43-96b9ea5ab8d1', 'SUPER_ADMINISTRATOR', 'SP', '2024-09-14 10:18:28.000000', 'SYSTEM', null, null, null, null);

INSERT INTO authorities(id, uuid, name, description, created_by,  created_at) VALUES
(1,'0fa2f861-1efc-4b26-9e45-d2b1d961c53b','ROLE_CREATE', '', 'SYSTEM', now()),
(2,'671b416d-c924-4d69-a221-2b5417dac494','ROLE_UPDATE', '', 'SYSTEM', now()),
(3,'07062f57-ed7b-42f9-a748-e7d01810eada','ROLE_GET', '', 'SYSTEM', now()),
(4,'0e7be079-4327-4195-a411-8baad3b6b41d','ROLE_FIND_BY_ID', '', 'SYSTEM', now()),
(5,'cd5e5ca1-71fd-4c3f-a2e0-bd3f13963627','ROLE_DELETE', '', 'SYSTEM', now()),
(6,'7b67cd0e-05db-46e8-b856-c60bf6254fe1','USER_CREATE', '', 'SYSTEM', now()),
(7,'4f37b3d1-2f2c-4763-a91e-8a41cf7a510f','USER_UPDATE', '', 'SYSTEM', now()),
(8,'26eccc42-ebcf-4946-be24-65d0fa8c88ad','USER_GET', '', 'SYSTEM', now()),
(9,'2aa4739c-3bf0-4664-8f01-06c658730a74','USER_FIND_BY_ID', '', 'SYSTEM', now()),
(10,'82ef1650-beec-4a95-93ab-1e1f070eee8d','USER_DELETE', '', 'SYSTEM', now()),
(11,'e1f95f7e-2ca0-40f5-9a98-841e99c9279d','MENU_GROUP_CREATE', '', 'SYSTEM', now()),
(12,'67e6fc23-dd25-4d8b-ad26-8a4acd06eb38','MENU_GROUP_UPDATE', '', 'SYSTEM', now()),
(13,'747163e3-66fd-445d-8e04-3cc256e82ccf','MENU_GROUP_GET', '', 'SYSTEM', now()),
(14,'8f2aea0d-2b5b-4a55-8588-7303e8f2f5e0','MENU_GROUP_FIND_BY_ID', '', 'SYSTEM', now()),
(15,'aeada9b3-7dba-4adf-921e-c6da32c8743c','MENU_GROUP_DELETE', '', 'SYSTEM', now()),
(16,'b9e93acf-bf9e-4e4e-b100-5d14dbcca075','MENU_ITEM_CREATE', '', 'SYSTEM', now()),
(17,'35080797-3c35-46d3-ad4f-7ca94497be46','MENU_ITEM_UPDATE', '', 'SYSTEM', now()),
(18,'5bb257e8-7f45-429d-a345-c3d46fb4ff37','MENU_ITEM_GET', '', 'SYSTEM', now()),
(19,'af7ba154-ac0c-4c81-bfe9-131452ce3850','MENU_ITEM_FIND_BY_ID', '', 'SYSTEM', now()),
(20,'ac7f8aa9-0d3c-4cb6-896f-3de14409138f','MENU_ITEM_DELETE', '', 'SYSTEM', now());

INSERT INTO user_roles (role_id, user_id) VALUES (1, 1);

INSERT INTO role_authorities(role_id, authority_id)
SELECT 1,id from authorities;

INSERT INTO menu_groups(id, uuid, module, name, sort_order, created_by, created_at)
VALUES (1, '99d6676e-0379-40bd-aabe-9608788dfa3e', 'SETUP', 'Settings', 1, 'SYSTEM', NOW());


INSERT INTO menu_items(id, uuid, name, state, sort_order, menu_group_id, created_by, created_at)
VALUES
(1, 'bcb47038-c49a-41f8-843d-194bbe51d3b4', 'Role', '/roles',1, 1,'SYSTEM', NOW()),
(2, '091f771b-b027-486b-b9c5-0e514abbd390', 'Menu Group', '/menu-groups',2, 1,'SYSTEM', NOW()),
(3, '923d9e3a-7773-4a30-9765-61cc2dc76331', 'Menu Items', '/menu-items',3, 1,'SYSTEM', NOW()),
(4, 'd90aab67-714c-4072-8d37-dea7047d195f', 'User', '/users',4, 1,'SYSTEM', NOW());

INSERT INTO menu_item_authorities(menu_item_id,authority_id)
VALUES
(1,1),
(2,11),
(3,16),
(4,6);



