CREATE TABLE roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID                                    NOT NULL,
    name       VARCHAR(100),
    code       VARCHAR(50),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(120),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(120),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(120),
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uc_roles_uuid UNIQUE (uuid),
    CONSTRAINT uc_roles_code UNIQUE (code),
    CONSTRAINT uc_roles_name UNIQUE (name)
);


CREATE TABLE users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid             UUID                                    NOT NULL,
    email            VARCHAR(120)                            NOT NULL,
    password         VARCHAR(255)                            NOT NULL,
    first_name       VARCHAR(120)                            NOT NULL,
    middle_name      VARCHAR(120),
    last_name        VARCHAR(120),
    sex              VARCHAR(10),
    mobile_number    VARCHAR(20),
    is_active        BOOLEAN,
    password_changed BOOLEAN,
    facility_id      UUID,
    facility_name    varchar(120),
    facility_code    varchar(20),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(120),
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_by       VARCHAR(120),
    deleted_at       TIMESTAMP WITHOUT TIME ZONE,
    deleted_by       VARCHAR(120),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_email UNIQUE (email),
    CONSTRAINT uc_users_uuid UNIQUE (uuid)
);

CREATE TABLE authorities
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID                                    NOT NULL,
    name        VARCHAR(120)                            NOT NULL,
    service     VARCHAR(120)                            NOT NULL,
    resource    VARCHAR(120)                            NOT NULL,
    action      VARCHAR(120)                            not null,
    method      VARCHAR(20),
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(120),
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_by  VARCHAR(120),
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_by  VARCHAR(120),
    CONSTRAINT pk_authorities PRIMARY KEY (id),
    CONSTRAINT uc_authorities_uuid UNIQUE (uuid)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id),
    CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id),
    CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE role_authorities
(
    authority_id BIGINT NOT NULL,
    role_id      BIGINT NOT NULL,
    CONSTRAINT pk_role_authorities PRIMARY KEY (authority_id, role_id),
    CONSTRAINT fk_rolaut_on_authority FOREIGN KEY (authority_id) REFERENCES authorities (id),
    CONSTRAINT fk_rolaut_on_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE menu_groups
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID                                    NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    icon       VARCHAR(255),
    sort_order INTEGER                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(255),
    CONSTRAINT pk_menu_groups PRIMARY KEY (id),
    CONSTRAINT uc_menu_groups_uuid UNIQUE (uuid)
);

CREATE TABLE menu_items
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID                                    NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    icon              VARCHAR(255),
    state             VARCHAR(255)                            NOT NULL,
    sort_order        INTEGER                                 NOT NULL,
    translation_label VARCHAR(255),
    menu_group_id     BIGINT                                  NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_by        VARCHAR(255),
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted_by        VARCHAR(255),
    CONSTRAINT pk_menu_items PRIMARY KEY (id),
    CONSTRAINT uc_menu_items_uuid UNIQUE (uuid),
    CONSTRAINT FK_MENU_ITEMS_ON_MENU_GROUP FOREIGN KEY (menu_group_id) REFERENCES menu_groups (id)
);

CREATE TABLE menu_item_authorities
(
    authority_id BIGINT NOT NULL,
    menu_item_id BIGINT NOT NULL,
    CONSTRAINT pk_menu_item_authorities PRIMARY KEY (authority_id, menu_item_id),
    CONSTRAINT fk_meniteaut_on_authority FOREIGN KEY (authority_id) REFERENCES authorities (id),
    CONSTRAINT fk_meniteaut_on_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_items (id)
);


