CREATE TABLE
  financial_years (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(120),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(120),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(120),
    CONSTRAINT pk_financial_years PRIMARY KEY (id),
    CONSTRAINT uc_financial_years_uuid UNIQUE (uuid),
    CONSTRAINT uc_financial_years_name UNIQUE (name),
    CONSTRAINT uc_financial_years_start_date UNIQUE (start_date),
    CONSTRAINT uc_financial_years_end_date UNIQUE (end_date)
  );
