CREATE TABLE
  professional_qualifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(120),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(120),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(120),
    CONSTRAINT pk_professional_qualifications PRIMARY KEY (id),
    CONSTRAINT uc_professional_qualifications_uuid UNIQUE (uuid),
    CONSTRAINT uc_professional_qualifications_name UNIQUE (name),
    CONSTRAINT uc_professional_qualifications_code UNIQUE (code)
  );
