CREATE TABLE
  risk_ranks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    min_value INTEGER NOT NULL,
    max_value INTEGER NOT NULL,
    color VARCHAR(10),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(120),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(120),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(120),
    CONSTRAINT pk_risk_ranks PRIMARY KEY (id),
    CONSTRAINT uc_risk_ranks_uuid UNIQUE (uuid),
    CONSTRAINT uc_risk_ranks_name UNIQUE (name)
  );
