CREATE TABLE
  departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(10),
    organisation_unit_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(120),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(120),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(120),
    CONSTRAINT pk_departments PRIMARY KEY (id),
    CONSTRAINT uc_departments_uuid UNIQUE (uuid),
    CONSTRAINT uc_departments_name UNIQUE (name),
    CONSTRAINT uc_departments_code UNIQUE (code),
    CONSTRAINT FK_departments_ON_organisation_units FOREIGN KEY (organisation_unit_id) REFERENCES organisation_units (id)
  );
