CREATE TABLE
  organisation_unit_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(10),
    position INTEGER NOT NULL,
    is_auditable_level BOOLEAN,
    is_risk_owner_level BOOLEAN,
    is_risk_register_level BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(120),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(120),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(120),
    CONSTRAINT pk_organisation_unit_levels PRIMARY KEY (id),
    CONSTRAINT uc_organisation_unit_levels_uuid UNIQUE (uuid),
    CONSTRAINT uc_organisation_unit_levels_name UNIQUE (name),
    CONSTRAINT uc_organisation_unit_levels_code UNIQUE (code)
  );
