CREATE TABLE
  finding_subcategories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(10) NOT NULL,
    finding_category_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(120),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(120),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(120),
    CONSTRAINT pk_finding_subcategories PRIMARY KEY (id),
    CONSTRAINT uc_finding_subcategories_uuid UNIQUE (uuid),
    CONSTRAINT uc_finding_subcategories_name UNIQUE (name),
    CONSTRAINT uc_finding_subcategories_code UNIQUE (code),
    CONSTRAINT FK_finding_subcategories_ON_finding_categories FOREIGN KEY (finding_category_id) REFERENCES finding_categories (id)
  );
