CREATE TABLE
  gfs_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    name VARCHAR(300) NOT NULL,
    code VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(120),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(120),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(120),
    CONSTRAINT pk_gfs_codes PRIMARY KEY (id),
    CONSTRAINT uc_gfs_codes_uuid UNIQUE (uuid),
    CONSTRAINT uc_gfs_codes_name UNIQUE (name),
    CONSTRAINT uc_gfs_codes_code UNIQUE (code)
  );
