CREATE TABLE
  periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    name VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    period_type VARCHAR(100) NOT NULL,
    financial_year_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(120),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(120),
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by VARCHAR(120),
    CONSTRAINT pk_periods PRIMARY KEY (id),
    CONSTRAINT uc_periods_uuid UNIQUE (uuid),
    CONSTRAINT uc_periods_name UNIQUE (name),
    CONSTRAINT FK_periods_ON_financial_years FOREIGN KEY (financial_year_id) REFERENCES financial_years (id)
  );
